# MongoDB config
spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce_db

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=electronce20@gmail.com
spring.mail.password=xuunpjgshiemkuyt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server port
server.port=8080
